#pragma once

#ifdef MSD_LANGUAGE_ENGLISH

#define MSDSTR_MENU							"Menu"
#define MSDSTR_OPEN							"Open"
#define MSDSTR_SAVE							"Save"
#define MSDSTR_MODEL						"Model"
#define MSDSTR_MODELPARAMETERS				"Model parameters"
#define MSDSTR_OBJECTTREE					"Object tree"
#define MSDSTR_MODELRUN						"Run model###Run"
#define MSDSTR_MODELSTOP					"Stop model###Run"
#define MSDSTR_RESULTS						"Results"
#define MSDSTR_MODELRESULTS					"Model results"
#define MSDSTR_VIEWPORT						"Viewport"
#define MSDSTR_MODELVIEWPORT				"Model viewport"
#define MSDSTR_TOOLS						"Tools"
#define MSDSTR_NOMAGNETRONS					"No magnetrons"
#define MSDSTR_ADDMAGNETRON					"Add magnetron"
#define MSDSTR_DELETEMAGNETRON				"Delete magnetron"
#define MSDSTR_NOMAGNETRONSERR				"It appears you didn't add any magnetrons.\n\nFor a proper calculation,add a magnetron in Model Parameters Window.\n"
#define MSDSTR_TIME							"Time (s)"
#define MSDSTR_TOTALDEPOSITED_PARTICLES		"Number of deposited atoms (1/m2)"
#define MSDSTR_TOTALDEPOSITED_METERS		"Deposited coating thickness (m)"
#define MSDSTR_TOTALDEPOSITED_MICROMETERS	"Deposited coating thickness (mcm)"
#define MSDSTR_TOTALDEPOSITED_NANOMETERS	"Deposited coating thickness (nm)"
#define MSDSTR_DEPOSITIONRATE_METERS		"Deposition rate (m/s)"
#define MSDSTR_TICKS						"Ticks: %d"
#define MSDSTR_SIMULATIONTIME				"Simulation time: %.2f s"
#define MSDSTR_TOTALMAGNETRONS				"Magnetrons in the model: %d"
#define MSDSTR_TOTALSUBSTRATES				"Substrates in the model: 1"
#define MSDSTR_FINISHWHEN					"Finish simulation when:"
#define MSDSTR_ROTATIONLIMIT				"Rotation Limit"
#define MSDSTR_TIMELIMIT					"Time Limit"
#define MSDSTR_TICKSPERSECOND				"Ticks Per Second"
#define MSDSTR_SHOWREALTIMEMOVEMENT			"Show real time movement of objects"
#define MSDSTR_ENABLEFLUXSCATTERING			"Enable flux scattering calculation"
#define MSDSTR_ANGMSD_STANDARD				"Standard"
#define MSDSTR_ANGMSD_REACTIVE				"Reactive"
#define MSDSTR_PRESSURE						"Pressure (Pa)"
#define MSDSTR_TEMPERATURE					"Temperature (K)"
#define MSDSTR_GAS							"Gas: %s"
#define MSDSTR_REACTIVEGAS					"Reactive gas: %s"
#define MSDSTR_REACTIVEGASRATIO				"Reactive gas ratio"
#define MSDSTR_RESULTSPARAMETERS			"Results parameters"
#define MSDSTR_DEPOSITEDUNITS				"Total deposited units"
#define MSDSTR_DEPOSITED_COMBO				"Total Particles\0Meters\0Micrometers\0Nanometers\0\0"
#define MSDSTR_MAGNETRON					"Magnetron"
#define MSDSTR_MAGNETRONPROPERTIES			"Magnetron properties"
#define MSDSTR_RADIUS						"Radius (cm)"
#define MSDSTR_MAGNETRONPOS					"Magnetron position (cm)"
#define MSDSTR_MAGNETRONNORMAL				"Magnetron normal vector"
#define MSDSTR_SUBSTRATE					"Substrate"
#define MSDSTR_ROTATECLOCKWISE				"Rotate clockwise"
#define MSDSTR_ROTATEAROUNDCENTER			"Rotate around Z"
#define MSDSTR_TARGETELEMENT				"Target element: %s"
#define MSDSTR_CALCSPUTRATES				"Calculate sput rates"
#define MSDSTR_USEFILE						"Use file"
#define MSDSTR_ENTERMAGNETRONPARAMETERS		"Enter magnetron parameters:"
#define MSDSTR_VOLTAGE						"Voltage (V)"
#define MSDSTR_CURRENT						"Current (A)"
#define MSDSTR_ENERGYTRANSMISSIONCOEFFS		"Energy transmission coefficients: "
#define MSDSTR_CURRENTCOEFF					"Current coefficient"
#define MSDSTR_VOLTAGECOEFF					"Voltage coefficient"
#define MSDSTR_SPUTTERINGYIELD				"Sputtering Yield :"
#define MSDSTR_SIGMUNDCALCULATION			"Sigmund calculation"
#define MSDSTR_MAGNETICFIELDDISTRIBUTION	"Magnetic field distribution"
#define MSDSTR_DISTANCEFROMCENTER			"distance from center (cm)"
#define MSDSTR_RADIALMAGNETICFIELD			"radial magnetic field (a.u.)"
#define MSDSTR_SPUTRATESINPUT				"Sput rates input:"
#define MSDSTR_SUBSTRATEPROPERTIES			"Substrate properties"
#define MSDSTR_SUBSTRATEPOS					"Substrate position"
#define MSDSTR_SUBSTRATENORMAL				"Substrate normal vector"
#define MSDSTR_RPM							"RPM"
#define MSDSTR_RPMHELP						"\"Rotations per minute\". \nSets the number of rotations of substrate around the origin."
#define MSDSTR_SUBRPM						"Sub RPM"
#define MSDSTR_SUBRPMHELP					"\"Substrate rotations per minute\". \nSets the number of rotations of substrate around its own axis."
#define MSDSTR_CM3F							"{:.3f} cm"
#define MSDSTR_SUBSTRATEDEPOSITIONEVOLUTION	"Substrate deposition evolution"
#define MSDSTR_OTHERRESULTS					"Other results:"
#define MSDSTR_MEANINCIDENTANGLE			"Mean incident angle: %.2f deg"
#define MSDSTR_DEPOSITIONFROMMAGNETRON		"Deposition from magnetron "
#define MSDSTR_SPUTTERINGRATE				"Sputtering rate: %.3f nm/s"
#define MSDSTR_MEANDEPOSITIONRATE			"Mean deposition rate: %.3f nm/s"
#define MSDSTR_EXPORTCSV					"Export CSV file"
#define MSDSTR_BROWSE						"Browse"
#define MSDSTR_SUCCESS						"Success!"
#define MSDSTR_CSVSAVED						"CSV file successfully saved\n\n"
#define MSDSTR_FILEERROR					"File Error"
#define MSDSTR_FILEPATHERROR_NOFILE			"Couldn't find the file for the magnetron.\nPlease make sure that the path is correct \n\n"
#define MSDSTR_FILEPATHERROR_FILECORRUPT	"An error occured while reading input file for the magnetron.\nPlease make sure that the file has correct format.\n\n"
#define MSDSTR_CHOOSEELEMENT				"Choose element: "
#define MSDSTR_ATOMICNUMBER					"Atomic number: %d"
#define MSDSTR_MEANENERGYEV					"Mean energy (eV)"
#define MSDSTR_ENERGYEV						"Energy (eV)"
#define MSDSTR_ATOMENERGYDISTRIBUTION		"Atom energy distribution"
#define MSDSTR_PROBABILITYDENSITY			"Probability Density"
#define MSDSTR_HELP							"Help"
#define MSDSTR_DEPRATETIMEDEPENDENCE		"Deposition rate in time dependence"
#define MSDSTR_PERCENTAGE					"Percentage"
#define MSDSTR_ELEMENT						"Element"
#define MSDSTR_COATINGCOMPOSITION			"Coating composition:"

#elif defined(MSD_LANGUAGE_RUSSIAN)

#define MSDSTR_MENU							(const char*)u8"Меню"
#define MSDSTR_OPEN							(const char*)u8"Открыть"
#define MSDSTR_SAVE							(const char*)u8"Сохранить"
#define MSDSTR_MODEL						(const char*)u8"Модель"
#define MSDSTR_MODELPARAMETERS				(const char*)u8"Параметры модели"
#define MSDSTR_OBJECTTREE					(const char*)u8"Обозреватель объектов"
#define MSDSTR_MODELRUN						(const char*)u8"Запустить###Run"
#define MSDSTR_MODELSTOP					(const char*)u8"Остановить###Run"
#define MSDSTR_RESULTS						(const char*)u8"Результаты"
#define MSDSTR_MODELRESULTS					(const char*)u8"Результаты модели"
#define MSDSTR_VIEWPORT						(const char*)u8"Отображение модели"
#define MSDSTR_MODELVIEWPORT				(const char*)u8"Отображение модели"
#define MSDSTR_TOOLS						(const char*)u8"Инструменты"
#define MSDSTR_NOMAGNETRONS					(const char*)u8"Нет магнетронов"
#define MSDSTR_ADDMAGNETRON					(const char*)u8"Добавить магнетрон"
#define MSDSTR_DELETEMAGNETRON				(const char*)u8"Удалить магнетрон"
#define MSDSTR_NOMAGNETRONSERR				(const char*)u8"Похоже, Вы не добавили магнетрон в модель.\n\nДля правильного расчёта, пожалуйста, добавьте магнетрон в окне параметров модели.\n"
#define MSDSTR_TIME							(const char*)u8"Время (с)"
#define MSDSTR_TOTALDEPOSITED_PARTICLES		(const char*)u8"Количество осаждённых атомов (1/м2)"
#define MSDSTR_TOTALDEPOSITED_METERS		(const char*)u8"Толщина осаждённого покрытия (м)"
#define MSDSTR_TOTALDEPOSITED_MICROMETERS	(const char*)u8"Толщина осаждённого покрытия (мкм)"
#define MSDSTR_TOTALDEPOSITED_NANOMETERS	(const char*)u8"Толщина осаждённого покрытия (нм)"
#define MSDSTR_DEPOSITIONRATE_METERS		(const char*)u8"Скорость осаждения (м/с)"
#define MSDSTR_TICKS						(const char*)u8"Количество тиков: %d"
#define MSDSTR_SIMULATIONTIME				(const char*)u8"Время расчёта: %.2f с"
#define MSDSTR_TOTALMAGNETRONS				(const char*)u8"Магнетронов в модели: %d"
#define MSDSTR_TOTALSUBSTRATES				(const char*)u8"Подложек в модели: 1"
#define MSDSTR_FINISHWHEN					(const char*)u8"Закончить расчёт когда:"
#define MSDSTR_ROTATIONLIMIT				(const char*)u8"Ограничение вращений"
#define MSDSTR_TIMELIMIT					(const char*)u8"Ограничение времени (с)"
#define MSDSTR_TICKSPERSECOND				(const char*)u8"Тиков в секунду"
#define MSDSTR_SHOWREALTIMEMOVEMENT			(const char*)u8"Показывать движение объектов в реальном времени"
#define MSDSTR_ENABLEFLUXSCATTERING			(const char*)u8"Учитывать рассеяние в рабочем газе"
#define MSDSTR_ANGMSD_STANDARD				(const char*)u8"Стандартная"
#define MSDSTR_ANGMSD_REACTIVE				(const char*)u8"Реактивная"
#define MSDSTR_PRESSURE						(const char*)u8"Давление (Па)"
#define MSDSTR_TEMPERATURE					(const char*)u8"Температура (К)"
#define MSDSTR_GAS							(const char*)u8"Рабочий газ: %s"
#define MSDSTR_REACTIVEGAS					(const char*)u8"Реактивный газ: %s"
#define MSDSTR_REACTIVEGASRATIO				(const char*)u8"Соотношение рабочего/реактивного газов"
#define MSDSTR_RESULTSPARAMETERS			(const char*)u8"Дополнительные параметры"
#define MSDSTR_DEPOSITEDUNITS				(const char*)u8"Единицы измерения осаждаемой плёнки"
#define MSDSTR_DEPOSITED_COMBO				(const char*)u8"Количество частиц\0Метры\0Микрометры\0Нанометры\0\0"
#define MSDSTR_MAGNETRON					(const char*)u8"Магнетрон"
#define MSDSTR_MAGNETRONPROPERTIES			(const char*)u8"Параметры магнетрона"
#define MSDSTR_RADIUS						(const char*)u8"Радиус (см)"
#define MSDSTR_MAGNETRONPOS					(const char*)u8"Расположение магнетрона (см)"
#define MSDSTR_MAGNETRONNORMAL				(const char*)u8"Вектор нормали"
#define MSDSTR_SUBSTRATE					(const char*)u8"Подложка"
#define MSDSTR_ROTATECLOCKWISE				(const char*)u8"Повернуть по часовой"
#define MSDSTR_ROTATEAROUNDCENTER			(const char*)u8"Повернуть вокруг Z"
#define MSDSTR_TARGETELEMENT				(const char*)u8"Элемент мишени: %s"
#define MSDSTR_CALCSPUTRATES				(const char*)u8"Рассчитать скорости распыления"
#define MSDSTR_USEFILE						(const char*)u8"Использовать файл"
#define MSDSTR_ENTERMAGNETRONPARAMETERS		(const char*)u8"Введите параметры магнетрона:"
#define MSDSTR_VOLTAGE						(const char*)u8"Напряжение (В)"
#define MSDSTR_CURRENT						(const char*)u8"Ток (A)"
#define MSDSTR_ENERGYTRANSMISSIONCOEFFS		(const char*)u8"Коэффициенты передачи энергии: "
#define MSDSTR_CURRENTCOEFF					(const char*)u8"Коэффициент тока"
#define MSDSTR_VOLTAGECOEFF					(const char*)u8"Коэффициент напряжения"
#define MSDSTR_SPUTTERINGYIELD				(const char*)u8"Коэффициент распыления:"
#define MSDSTR_SIGMUNDCALCULATION			(const char*)u8"Расчёт по Зигмунду"
#define MSDSTR_MAGNETICFIELDDISTRIBUTION	(const char*)u8"Распределение магнитного поля"
#define MSDSTR_DISTANCEFROMCENTER			(const char*)u8"Расстояние от центра (см)"
#define MSDSTR_RADIALMAGNETICFIELD			(const char*)u8"Радиальное магнитное поле (отн.ед.)"
#define MSDSTR_SPUTRATESINPUT				(const char*)u8"Ввод скоростей распыления:"
#define MSDSTR_SUBSTRATEPROPERTIES			(const char*)u8"Параметры подложки"
#define MSDSTR_SUBSTRATEPOS					(const char*)u8"Расположение подложки (см)"
#define MSDSTR_SUBSTRATENORMAL				(const char*)u8"Вектор нормали"
#define MSDSTR_RPM							(const char*)u8"Вр.в мин."
#define MSDSTR_RPMHELP						(const char*)u8"Количество вращений подложки в минуту вокруг центра"
#define MSDSTR_SUBRPM						(const char*)u8"Собств. вр. в мин."
#define MSDSTR_SUBRPMHELP					(const char*)u8"Количество вращений подложки в минуту вокруг своей оси"
#define MSDSTR_CM3F							"{:.3f} cm"
#define MSDSTR_SUBSTRATEDEPOSITIONEVOLUTION	(const char*)u8"Рост покрытия на подложке"
#define MSDSTR_OTHERRESULTS					(const char*)u8"Прочие результаты:"
#define MSDSTR_MEANINCIDENTANGLE			(const char*)u8"Средний угол падения потока: %.2f град."
#define MSDSTR_DEPOSITIONFROMMAGNETRON		(const char*)u8"Осаждение от магнетрона "
#define MSDSTR_SPUTTERINGRATE				(const char*)u8"Скорость распыления: %.3f м/с"
#define MSDSTR_MEANDEPOSITIONRATE			(const char*)u8"Средняя скорость осаждения: %.3f нм/с"
#define MSDSTR_MEANATOMENERGY				(const char*)u8"Средняя энергия атомов: %.3f эВ"
#define MSDSTR_EXPORTCSV					(const char*)u8"Экспорт CSV файла"
#define MSDSTR_BROWSE						(const char*)u8"Открыть"
#define MSDSTR_SUCCESS						(const char*)u8"Успешно"
#define MSDSTR_CSVSAVED						(const char*)u8"CSV файл успешно сохранён\n\n"
#define MSDSTR_FILEERROR					(const char*)u8"Ошибка файла"
#define MSDSTR_FILEPATHERROR_NOFILE			(const char*)u8"Невозможно найти указанный файл.\nПожалуйста, убедитесь, что указан верный путь.\n\n"
#define MSDSTR_FILEPATHERROR_FILECORRUPT	(const char*)u8"Произошла ошибка при чтении файла для магнетрона.\nПожалуйста, убедитесь, что файл имеет корректный формат.\n\n"
#define MSDSTR_CHOOSEELEMENT				(const char*)u8"Выберите элемент: "
#define MSDSTR_ATOMICNUMBER					(const char*)u8"Атомный номер: %d"
#define MSDSTR_MEANENERGYEV					(const char*)u8"Средняя энергия (эВ)"
#define MSDSTR_ENERGYEV						(const char*)u8"Энергия (эВ)"
#define MSDSTR_ATOMENERGYDISTRIBUTION		(const char*)u8"Распределение энергии атомов"
#define MSDSTR_PROBABILITYDENSITY			(const char*)u8"Плотность вероятности"
#define MSDSTR_HELP							(const char*)u8"Помощь"
#define MSDSTR_DEPRATETIMEDEPENDENCE		(const char*)u8"Скорость осаждения от времени"
#define MSDSTR_PERCENTAGE					(const char*)u8"Процентное содержание"
#define MSDSTR_ELEMENT						(const char*)u8"Элемент"
#define MSDSTR_COATINGCOMPOSITION			(const char*)u8"Состав покрытия:"

#endif